# Generated by Django 4.2.3 on 2023-08-29 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0002_remove_organization_name_requisite_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='adres',
            options={'verbose_name_plural': 'Адреса фирм'},
        ),
        migrations.AlterModelOptions(
            name='organization',
            options={'verbose_name_plural': 'Организации'},
        ),
        migrations.AlterModelOptions(
            name='requisite',
            options={'verbose_name_plural': 'Реквизиты'},
        ),
        migrations.AlterField(
            model_name='adres',
            name='city',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Город'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='house',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Дом'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='index',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Индекс'),
        ),
        migrations.AlterField(
            model_name='adres',
            name='street',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Улица'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='active',
            field=models.BooleanField(default=False, verbose_name='Активация'),
        ),
        migrations.AlterField(
            model_name='organization',
            name='requisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.requisite', verbose_name='Реквизиты'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='adres',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.adres', verbose_name='Адрес'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='name',
            field=models.CharField(max_length=150, verbose_name='Наименование'),
        ),
    ]
