# Generated by Django 4.2.3 on 2023-08-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_alter_requisite_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='requisite',
            name='name',
        ),
        migrations.AddField(
            model_name='organization',
            name='name',
            field=models.CharField(default=0, max_length=150, unique=True, verbose_name='Наименование'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='requisite',
            name='telephone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
