# Generated by Django 4.2.3 on 2023-09-06 12:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0007_alter_requisite_options_remove_requisite_adres_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organization',
            name='requisite',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='organization.requisite', verbose_name='Банковские реквизиты'),
        ),
        migrations.AlterField(
            model_name='requisite',
            name='inn_nomber',
            field=models.IntegerField(blank=True, max_length=20, null=True, verbose_name='ИНН'),
        ),
    ]
