# Generated by Django 4.2.3 on 2023-08-20 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_production', models.DateField(editable=False, verbose_name='Дата производства')),
            ],
        ),
        migrations.CreateModel(
            name='ViewMonitoringObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, unique=True, verbose_name='Вид')),
            ],
            options={
                'verbose_name_plural': 'Вид объекта',
            },
        ),
        migrations.CreateModel(
            name='TypeMonitoringObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.viewmonitoringobject', verbose_name='Вид')),
            ],
            options={
                'verbose_name_plural': 'Тип объекта',
            },
        ),
        migrations.CreateModel(
            name='BaseMonitoringObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_number', models.IntegerField(editable=False, unique=True, verbose_name='Уникальный номер')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='Наименование')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата создания')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tool.typemonitoringobject', verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Базовый класс',
            },
        ),
    ]
