# Generated by Django 4.2.3 on 2023-08-20 20:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='id',
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='id_number',
            field=models.IntegerField(editable=False, primary_key=True, serialize=False, unique=True, verbose_name='Уникальный номер'),
        ),
    ]
