# Generated by Django 4.2.3 on 2023-08-14 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='id_nomber',
            field=models.IntegerField(editable=False, unique=True),
        ),
    ]
