# Generated by Django 4.2.3 on 2023-08-06 14:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='view',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='tool.viewequipment'),
        ),
    ]
