# Generated by Django 4.2.3 on 2023-08-22 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_rename_id_nomber_qrcode_unique_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='qrcode',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.qrcode', verbose_name='QRcode'),
        ),
    ]
