# Generated by Django 4.2.3 on 2023-08-14 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_alter_basemonitoringobject_id_nomber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='basemonitoringobject',
            old_name='id_nomber',
            new_name='id_number',
        ),
    ]
