# Generated by Django 4.2.3 on 2023-08-20 20:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0002_remove_basemonitoringobject_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.production', verbose_name='Произведено'),
        ),
    ]
