# Generated by Django 4.2.3 on 2023-08-06 14:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_alter_typeequipment_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='typeequipment',
            name='view',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.viewequipment'),
        ),
    ]
