# Generated by Django 4.2.3 on 2023-08-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_basemonitoringobject_product'),
    ]

    operations = [
        migrations.AlterField(
            model_name='production',
            name='date_production',
            field=models.DateField(verbose_name='Дата производства'),
        ),
    ]
