# Generated by Django 4.2.3 on 2023-08-15 07:40

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0003_rename_id_nomber_basemonitoringobject_id_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='update_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
