# Generated by Django 4.2.3 on 2023-08-20 20:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_production_date_production'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='monitoring_objects', to='tool.production', verbose_name='Произведено'),
        ),
    ]
