# Generated by Django 4.2.3 on 2023-08-06 14:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_alter_typeequipment_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='view',
        ),
    ]
