# Generated by Django 4.2.3 on 2023-08-15 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0004_basemonitoringobject_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='create_date',
            field=models.DateField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='update_date',
            field=models.DateField(auto_now_add=True),
        ),
    ]
