# Generated by Django 4.2.3 on 2023-08-07 08:34

from django.db import migrations, models
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0005_remove_basemonitoringobject_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='name',
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='view',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.viewequipment'),
            preserve_default=False,
        ),
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='type',
        ),
        migrations.RemoveField(
            model_name='typeequipment',
            name='view',
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='type',
            field=smart_selects.db_fields.ChainedManyToManyField(chained_field='ViewEquipment', chained_model_field='view', horizontal=True, to='tool.typeequipment', verbose_name='TypeEquipment'),
        ),
        migrations.AddField(
            model_name='typeequipment',
            name='view',
            field=models.ManyToManyField(blank=True, null=True, to='tool.viewequipment'),
        ),
    ]
