# Generated by Django 4.2.3 on 2023-08-20 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_basemonitoringobject_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='production',
            name='user',
            field=models.CharField(default=0, max_length=100, verbose_name='Тип'),
            preserve_default=False,
        ),
    ]
