# Generated by Django 4.2.3 on 2023-08-15 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_basemonitoringobject_create_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='create_date',
            field=models.DateField(editable=False),
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='update_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
