# Generated by Django 4.2.3 on 2023-08-23 09:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_alter_basemonitoringobject_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='production',
            options={'verbose_name_plural': 'Производство'},
        ),
        migrations.AlterModelOptions(
            name='qrcode',
            options={'verbose_name_plural': 'Уникальная регистрация'},
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата производства'),
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='qrcode',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.qrcode', verbose_name='QRcode'),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='unique_number',
            field=models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Уникальный номер'),
        ),
    ]
