# Generated by Django 4.2.3 on 2023-08-07 08:41

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0006_remove_basemonitoringobject_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='type',
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='ViewEquipment', chained_model_field='view', default=0, on_delete=django.db.models.deletion.CASCADE, to='tool.typeequipment'),
            preserve_default=False,
        ),
    ]
