# Generated by Django 4.2.3 on 2023-08-20 21:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_production_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='product',
        ),
        migrations.AddField(
            model_name='production',
            name='related_monitoring_object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='productions', to='tool.basemonitoringobject'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='production',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Пользователь'),
        ),
    ]
