# Generated by Django 4.2.3 on 2023-08-15 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_basemonitoringobject_create_date_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VibratingTamper',
            fields=[
                ('basemonitoringobject_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='tool.basemonitoringobject')),
            ],
            bases=('tool.basemonitoringobject',),
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='days_warranty',
            field=models.IntegerField(default=365, verbose_name='Ост. дней гарантии'),
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='start_date_use',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='update_date',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
