# Generated by Django 4.2.3 on 2023-08-24 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_alter_production_options_alter_qrcode_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pasrametrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
