# Generated by Django 4.2.3 on 2023-08-07 08:43

from django.db import migrations
import django.db.models.deletion
import smart_selects.db_fields


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0007_remove_basemonitoringobject_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='type',
            field=smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='TypeEquipment', chained_model_field='name', on_delete=django.db.models.deletion.CASCADE, to='tool.typeequipment'),
        ),
    ]
