# Generated by Django 4.2.3 on 2023-08-24 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_pasrametrs'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pasrametrs',
            new_name='Parametrs',
        ),
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='create_date',
        ),
        migrations.RemoveField(
            model_name='production',
            name='date_production',
        ),
        migrations.AddField(
            model_name='production',
            name='create_date',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Дата производства'),
        ),
    ]
