# Generated by Django 4.2.3 on 2023-08-15 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_vibratingtamper_basemonitoringobject_days_warranty_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='days_warranty',
        ),
    ]
