# Generated by Django 4.2.3 on 2023-08-07 08:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_alter_basemonitoringobject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='type',
        ),
    ]
