# Generated by Django 4.2.3 on 2023-08-20 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0008_remove_basemonitoringobject_product_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='related_monitoring_object',
        ),
        migrations.AddField(
            model_name='production',
            name='object',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='tool.basemonitoringobject', verbose_name='Продукт'),
            preserve_default=False,
        ),
    ]
