# Generated by Django 4.2.3 on 2023-08-24 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_rename_pasrametrs_parametrs_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='production',
            name='object',
        ),
        migrations.AddField(
            model_name='basemonitoringobject',
            name='production',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tool.production', verbose_name='Производство'),
        ),
    ]
