# Generated by Django 4.2.3 on 2023-08-21 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_remove_production_related_monitoring_object_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='id_number',
            field=models.CharField(editable=False, max_length=12, unique=True, verbose_name='Уникальный номер'),
        ),
    ]
