# Generated by Django 4.2.3 on 2023-08-07 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0009_remove_basemonitoringobject_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.typeequipment'),
            preserve_default=False,
        ),
    ]
