# Generated by Django 4.2.3 on 2023-08-07 08:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_basemonitoringobject_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='typeequipment',
            name='view',
        ),
        migrations.AddField(
            model_name='typeequipment',
            name='view',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='tool.viewequipment'),
            preserve_default=False,
        ),
    ]
