# Generated by Django 4.2.3 on 2023-08-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0010_guarantee'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='end_warranty',
            field=models.DateField(blank=True, editable=False, null=True),
        ),
    ]
