# Generated by Django 4.2.3 on 2023-08-07 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0011_remove_typeequipment_view_typeequipment_view'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='basemonitoringobject',
            name='view',
        ),
    ]
