# Generated by Django 4.2.3 on 2023-08-07 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0012_remove_basemonitoringobject_view'),
    ]

    operations = [
        migrations.AddField(
            model_name='basemonitoringobject',
            name='name',
            field=models.CharField(default=0, max_length=100),
            preserve_default=False,
        ),
    ]
