# Generated by Django 4.2.3 on 2023-08-07 18:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0016_alter_typeequipment_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='name',
            field=models.CharField(db_column='Наименование модели', max_length=100),
        ),
    ]
