# Generated by Django 4.2.3 on 2023-08-07 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tool', '0017_alter_basemonitoringobject_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='UniqueIdentificator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomber', models.TextField(max_length=16, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='basemonitoringobject',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='typeequipment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='viewequipment',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
