# Generated by Django 4.2.3 on 2023-08-30 10:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0004_customuser_organization'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Parametrs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='QRCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.CharField(blank=True, editable=False, max_length=6, null=True, unique=True, verbose_name='Уникальный номер')),
            ],
            options={
                'verbose_name_plural': 'Уникальная регистрация',
            },
        ),
        migrations.CreateModel(
            name='ViewMonitoringObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('view_name', models.CharField(max_length=100, unique=True, verbose_name='Вид')),
            ],
            options={
                'verbose_name_plural': 'Вид объекта',
            },
        ),
        migrations.CreateModel(
            name='TypeMonitoringObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type_name', models.CharField(max_length=100, verbose_name='Тип')),
                ('view', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.viewmonitoringobject', verbose_name='Вид')),
            ],
            options={
                'verbose_name_plural': 'Тип объекта',
            },
        ),
        migrations.CreateModel(
            name='Production',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_date', models.DateField(auto_now_add=True, null=True, verbose_name='Дата производства')),
                ('collector', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Сборщик')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='organization.organization', verbose_name='Организация')),
            ],
            options={
                'verbose_name_plural': 'Производство',
            },
        ),
        migrations.CreateModel(
            name='BaseMonitoringObject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Наименование')),
                ('active', models.BooleanField(default=False)),
                ('production', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.production', verbose_name='Производство')),
                ('qrcode', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='production.qrcode', verbose_name='QRcode')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='production.typemonitoringobject', verbose_name='Тип')),
            ],
            options={
                'verbose_name_plural': 'Базовый класс',
            },
        ),
    ]
